### PR TITLE
Fix lookup/lookdown speed and angles

### PR DESCRIPTION
**Pull request by erysdren**
Turns out it wasn't #61 that fixed the demo desync in ROTTEN, it was this change I made. Here's a video showing it in action:

https://www.youtube.com/watch?v=EkmBAkH_o-E

### CODE REVIEW

**Review by fabiangreffrath — APPROVED** [review]
Great, thank you! Is this resolution independent?

**Comment by erysdren** [comment]
Hmm, it's probably not resolution independent... however, I tested demo 1 at 640x480 and it still worked just fine and played to the end, so maybe it's okay. if we ever add resolutions other than 320x200 and 640x480 it can become a problem then.

**Comment by fabiangreffrath** [comment]
BTW, which demo is this?

**Comment by erysdren** [comment]
`demo1_3.dmo`, which is the first one you can select in the demo playback cheat menu.

**Review by fabiangreffrath — APPROVED** [review]

**Pull request merged**
