### PR TITLE
Remove old & confusing macros

### PR DESCRIPTION
**Pull request by erysdren**
This is just general code cleanup. I'd also like to work on the DOPEFISH and SHAREWARE macros, but pruning those (while keeping the functionality) is a much more involved process.

### CODE REVIEW

**Review by fabiangreffrath — APPROVED** [review]
Thanks for this!

**Comment by erysdren** [comment]
oops. one sec

**Comment by erysdren** [comment]
@fabiangreffrath Do you want me to merge this now, or do you want me to work on it more? This could become the "general code cleanup" PR, or I could merge this one and do another one later on. There's an endless amount of cleanup to do, but I've tackled the most obvious things I've seen so far here.

**Comment by fabiangreffrath** [comment]
I'm fine if you merge this now. We don't need to clean out the entire code base in just one commit. 😉

**Pull request merged**
